### ISSUE TITLE
transports can't be converted to a sequence (JS error if there is already an enrollment)

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/fido2#1]
I cannot have more than 1 fido2 key enrolled in Casa for the same user. The first enrollment succeeds but subsequent attempts throw error.

It does not matter which key I enroll first. Or if the browser session is fresh. Actually the error is shown even if I don't plug a key into the USB port.

The error is thrown in the javascript call `webauthn.createCredential(request)` see:
![Screenshot from 2020-06-20 14-23-40](https://user-images.githubusercontent.com/5444180/85210178-5fb20f00-b303-11ea-96fc-ad9be38bea99.png)

`transports` property is null in `excludeCredentials`.

In fido2 impl of CE 4.1 it was possible to enroll _n_ fido2 keys.

**Comment by yurem** [comment]
Yes, transport null value should be excluded
Than you for hint

**Comment by yurem** [comment]
Fixed
